GET https://8080-pink-crane-0lbn29ks.ws-us18.gitpod.io/filmes

###

POST https://8080-pink-crane-0lbn29ks.ws-us18.gitpod.io/filmes
Content-Type: application/json

{
    "titulo" : "Exemplo"
}

###

PUT https://8080-pink-crane-0lbn29ks.ws-us18.gitpod.io/filmes/5
Content-Type: application/json

{
    "titulo" : "GhostBusters"
}